Add minimum feerate to TooLowFeerate error message
wizardsardine/liana pull request #1186
Opened 2024-07-10 08:25 UTC by aaroncarlucci

This PR adds the minimum feerate value into the `TooLowFeerate` error message for additional context. Addresses the second bullet point in #853.

2024-07-10 12:38 UTC, jp1ac4 requested changes
Thanks very much for this PR.

One small thing: Could you please run the [black](https://github.com/psf/black) formatter on the Python test file as I think one of the lines is slightly too long now. Thanks.

2024-07-10 12:59 UTC, aaroncarlucci commented
Np. Ran `black` and changes force-pushed.

2024-07-10 13:16 UTC, jp1ac4 approved these changes
ACK 8be0d9856b29eb30593ae7614fe74430ffd206d4. Thanks!

2024-07-29 11:51 UTC, darosior commented
Cool, thanks! My bad for not being too responsive with merging this.

2024-07-29 11:53 UTC, merged