#858: Change text when downloading Bitcoin to include version number
wizardsardine/liana pull request #912
Opened 2024-01-11 19:13 UTC by acarlton

Simple text change to add bitcoind version number to download wording as per #858. First issue exploration.

2024-01-11 21:57 UTC, pythcoiner commented
ACK  d2ef685595dc393b148ed27c16311d302a11a9d1 (tested on signet)

![image](https://github.com/wizardsardine/liana/assets/124568858/44b0d0d5-520a-4e21-926d-fb513a54a77b)

2024-01-12 17:18 UTC, jp1ac4 requested changes
Thanks for this PR.

There's a small change to the wording needed. You can squash your commits already when making that change. Thanks.

2024-01-12 17:18 UTC, jp1ac4 commented on gui/src/installer/view.rs
> +                            "Downloading Bitcoin {version}... {progress:.2}%"
Could you please change it to "Bitcoin Core".

2024-01-12 18:15 UTC, jp1ac4 approved these changes
ACK https://github.com/wizardsardine/liana/commit/b4f505c4312c3ef4c54dde82a940e923c2b3ca1d.

![image](https://github.com/wizardsardine/liana/assets/121959000/a11baf71-7b08-40c3-8507-6200b4eaa6b5)

2024-01-12 23:09 UTC, pythcoiner commented
ACK b4f505c4312c3ef4c54dde82a940e923c2b3ca1d

2024-01-13 10:50 UTC, merged

2024-01-13 10:51 UTC, darosior commented
Thanks!